<?php

/**
* Clusterpoint manager class
*/
class ClusterPoint extends CouchDB {
	
	public function create($item) {
	    $url = 'https://api-eu.clusterpoint.com/v4/4219/stats';
	    $userPassword = 'savanramani255@gmail.com:Swift123';

    	$doc = array(
	        'item_id' => $item["id"],
	        'user_id' => $item["user_id"],
	        'click' => 1,
	        'timestamp' => time()
	    );

	    $ch = curl_init();
	    // https://api-eu.clusterpoint.com/v4/ACCOUNT_ID/DATABASE_NAME[ID]     -  Insert single document with explicit ID
	    curl_setopt($ch, CURLOPT_URL, $url); //  In this case document ID is automatically generated by system.
	    curl_setopt($ch, CURLOPT_USERPWD, $userPassword);
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
	    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
	    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($doc));
	    $response = curl_exec($ch);
	    $errorMsg = curl_error($ch);
	    if ($errorMsg) {
	        var_dump($errorMsg);
	    }
	    curl_close($ch);
	}

	public function read($item) {
		$url = 'https://api-eu.clusterpoint.com/v4/4219/stats';
	    $userPassword = 'savanramani255@gmail.com:Swift123';

		$ch = curl_init();
		$query = "SELECT * FROM stats WHERE item_id == '".$item["id"]."' && user_id == '".$item["user_id"]."' LIMIT 1";

		curl_setopt($ch, CURLOPT_URL, $url . '/_query'); // We added _query here!
		curl_setopt($ch, CURLOPT_USERPWD, $userPassword);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
		$response = json_decode(curl_exec($ch));
		curl_close($ch);

		return isset($response->results) ? $response->results : NULL;
	}

	public function update($id, $click) {
		$url = 'https://api-eu.clusterpoint.com/v4/4219/stats';
	    $userPassword = 'savanramani255@gmail.com:Swift123';

		$query = 'UPDATE stats["' . $id . '"] SET click = "' . $click . '"';
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url . '/_query');
		curl_setopt($ch, CURLOPT_USERPWD, $userPassword);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST"); // or use PATCH request  https://www.clusterpoint.com/docs/?page=Update
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
		$response = curl_exec($ch);
		$errorMsg = curl_error($ch);
		if ($errorMsg) {
			var_dump($errorMsg);
		}
		curl_close($ch);
	}
}