<?php
define("URL", "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]");
$item_id = $_GET['item'];

$str = base64_decode($item_id);
$datas = explode("&", $str);
foreach ($datas as $data) {
    $property = explode("=", $data);
    $item[$property[0]] = $property[1];
}

function send($id) {
    $url = 'https://api-eu.clusterpoint.com/v4/2538/FraudLinks';
    $userPassword = 'info@earnbugs.in:Swift123';

    $doc = array(
        'item' => $id,
        'timestamp' => time()
    );

    $ch = curl_init();
    // https://api-eu.clusterpoint.com/v4/ACCOUNT_ID/DATABASE_NAME[ID]     -  Insert single document with explicit ID
    curl_setopt($ch, CURLOPT_URL, $url); //  In this case document ID is automatically generated by system.
    curl_setopt($ch, CURLOPT_USERPWD, $userPassword);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($doc));
    $response = curl_exec($ch);
    $errorMsg = curl_error($ch);
    if ($errorMsg) {
        var_dump($errorMsg);
    }
    curl_close($ch);
}
?>

<!DOCTYPE html>
<html>

<head>
    <meta property="fb:app_id" content="1644257145856201">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="robots" content="noodp">
    <meta property="og:title" content="<?php echo $item['title']?>" />
    <meta property="og:locale" content="en_US">
    <meta property="og:type" content="article">
    <meta property="og:description" content="<?php echo $item['title']?>">
    <meta property="og:url" content="<?php echo URL;?>">
    <meta property="og:image" content="http://www.earnbugs.in/public/assets/uploads/images/<?php echo $item['image'];?>">
    <meta name="og:image-new" content="http://www.earnbugs.in/public/assets/uploads/images/<?php echo $item['image'];?>">
    <meta property="og:site_name" content="The EarnBugs Media Group">
    <meta name="generator" content="SwiftMVC 1.1.1">
    <!--<meta http-equiv="refresh" content="0;<?php echo $item['url'];?>">-->
</head>

<body>

    <script type="text/javascript">
        function setCookie(cname, cvalue, exdays) {
            var d = new Date();
            d.setTime(d.getTime() + (exdays*24*60*60*1000));
            var expires = "expires="+d.toUTCString();
            document.cookie = cname + "=" + cvalue + "; " + expires;
        }

        function getCookie(cname) {
            var name = cname + "=";
            var ca = document.cookie.split(';');
            for(var i=0; i<ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0)==' ') c = c.substring(1);
                if (c.indexOf(name) == 0) return c.substring(name.length, c.length);
            }
            return "";
        }

        function track () {
            var cookie = 'track_'+'<?php echo $item["id"];?>';
            var track = getCookie(cookie);
            if (track != "") {
                //cookie exists
                if(track >= 6) {
                    //send fraud detection to server
                    report();
                } else {
                    setCookie(cookie, ++track, 1);
                }
            } else {
                setCookie(cookie, 1, 1);
            }
        }

        function report () {
            console.log('<?php send($item["id"]);?>');
        }

        track();
        window.location.href = '<?php echo $item["url"];?>';
    </script>
</body>

</html>